### ISSUE TITLE
Unable to close PseudoTV 

### ISSUE THREAD

**Issue by Alexwijn** [Lunatixz/script.pseudotv.live#26]
After pressing the stop or exit button I'm returning to the skin dashboard and then it freezes kodi. It is stuck with the TV logo at the bottom right.

I'm forced to kill the kodi process before I can use it again. 

Is this a know issue or am I the first?

**Comment by StormPooper** [comment]
:+1: This happens for me on pressing Stop, but not when pressing Exit and selecting 'Yes' on the prompt.

**Comment by StormPooper** [comment]
Update: Fixed for me as of v0.5.8f.

**Comment by Alexwijn** [comment]
Confirmed that it is fixed!
