### ISSUE TITLE
Play TV show in order not grouping multi-part episodes

### ISSUE THREAD

**Issue by StormPooper** [Lunatixz/script.pseudotv.live#27]
I have configured my channels to use the 'Play TV show in order' rule in combination with playing random episodes (as per #21), but multipart episodes are not played in order. Here's an example of a channel from my config file:
```
<setting id="Channel_1_type" value="6" />
<setting id="Channel_1_1" value="Show Name" />
<setting id="Channel_1_2" value="0" />
<setting id="Channel_1_changed" value="False" />
<setting id="Channel_1_rulecount" value="1" />
<setting id="Channel_1_rule_1_id" value="12" />
```

**Comment by Lunatixz** [comment]
are you talking about "stacked" videos, ie. myshow.cd1.avi, myshow.cd2.avi?
if the above is what you want, you need to enable multipart "stack" in kodi, then PTVL picks up the "stack://" protocol kodi adds to the file.

**Comment by StormPooper** [comment]
No, I'm talking about two-part episodes, as in the story continues into the
next week.

**Comment by StormPooper** [comment]
Any idea as to why two-part episodes (as in the story continues into the next episode) aren't played next to each other? In #21 the fix mentioned was to apply 'Play TV show in order', but this doesn't fix it, they just appear randomly.

**Comment by Lunatixz** [comment]
Read FAQ in post 3 @.org

**Comment by StormPooper** [comment]
Can you provide a link? I can only find a .com site, which doesn't have an FAQ, and the XBMC.org post links to the .com address.
