### ISSUE TITLE
Autotune is broken

### ISSUE THREAD

**Issue by arctelix** [Lunatixz/script.pseudotv.live#32]
Hey Luna, This plugin could be a life changer, Amazing work!

Just getting started with pseudotv live and as of the latest version 0.6.1b autotune seems to be broken for community lists and playon.

I was about to submit a pull request and realized that github master is at 0.6.1 and it auto updates to 0.6.1b.  It seems that opting out of autoupdate does not work.  In either case the same issues are present.

The main issue is the urls changed in ``ChannelList.py`` to ``http://raw.github.com/`` which are not valid. The valid path is:
```
https://raw.githubusercontent.com/Lunatixz/PseudoTV_Lists/master/
```
I assume this is a very temp location, probably not a good idea to host static files on github.

Also, I was having issues with playon, then fixed it with the following mod to``ChannelList.py``:
```
4478: try:
4479:     PluginName = (xbmcaddon.Addon(id=PluginPath)).getAddonInfo('name')
4480: except:
4481:     PluginName = ''

4534: self.updateDialog.update(self.updateDialogProgress, "Updating channel " + str(self.settingChannel), "Parsing " + (xName), "found " + label)
```

Also,  version 0.6.1b has an issue with ``utils.py`` line 712 ``TypeError: attribute of type 'NoneType' is not callable``, this seems to be a python bug only found in kodi addons (weird).  The following line will accomplish the same thing without risk of this bug:
```
# replace this line
712: SyncPTV = datetime.datetime.strptime(SyncPTV_LastRun, "%Y-%m-%d %H:%M:%S.%f")
# with this line
712:  SyncPTV = datetime.datetime.fromtimestamp(0)
```

Master ``default.py`` tries to import ``resources.lib.ga`` rather then ``resources.lib.ga``.

It's hard to figure out which version is the latest. Any help shedding light on whats going on with the versions and differences to github master would be appricated.

Thanks for a great plugin!

**Comment by alibbaba** [comment]
Also i am getting this error, which obviously should be >upnp . I just download version on the github master.             
>File "C:\Users\Alias\AppData\Roaming\XBMC\addons\script.pseudotv.live-master\resources\lib\Overlay.py", line 34, in <module>
                                                from Upnp import Upnp
                                            ImportError: No module named Upnp

**Comment by rafaelvieiras** [comment]
Also i am getting this error, but i remove line '712: SyncPTV'. It's Bad, but solved my problem.
