### ISSUE TITLE
PseudoTV Causes Kodi To Hang When Exiting

### ISSUE THREAD

**Issue by brando56894** [Lunatixz/script.pseudotv.live#34]
PseudoTV hangs indefinitely/for a few minutes when closing Kodi on Windows 7 & 10, I usually have to go into the task manager to kill Kodi because it freezes solid. This has been happening for a while with various builds of Kodi/XBMC and PseudoTV Live.

I'm currently using Kodi 14.2 and PTV Live 0.6.1e

This is definitely an issue with PseudoTV Live because I created a new Kodi profile and only installed PTV and it's dependencies. After it installed I closed Kodi immediately and it exited within about 5 seconds like it should. I copied over my settings and opened Kodi again, then exited but it hung this time. Thinking it was maybe my settings, I deleted the pseudtotv userdata folder and it still hung. I deleted the PTV addon but left all of the dependencies and it exited like it should. I reinstalled PTV and immediately exited once again, everything was fine. I started Kodi once again (not copying anything over this time) and exited, and it hung for a good 2 minutes before exiting by itself.

Here's a few debug logs that I collected
[PseudoTV Installed] (http://pastebin.com/d4um7dP5 )
[PseudoTV Removed] (http://pastebin.com/vbNtpQ3e )

Edit: Just for the hell of it, I created a clean profile and this time installed PseudoTV Lite and closed Kodi immediately, everything was fine. Opened Kodi back up and closed it again after waiting a few seconds, it exited within about 5 seconds. Just to be sure I opened Kodi up again, waited about 30 seconds and then exited, it closed within about 5-10 seconds. So it seems the bug lies within the additional features of PseudoTV Live.

[PseudoTV Lite Debug Log] (http://pastebin.com/gvX6q84M)

**Comment by jamesdwilson** [comment]
Maybe related: When existing from PSTVL on OSMC/Kodi on Raspi2, it takes forever to exit, most time taken during "saving"

**Comment by Lunatixz** [comment]
It's a mix of threading not closing properly and the PTVL's background service hanging...
New update fixes most of the problems... should be completely fixed by the next few updates...

**Comment by jamesdwilson** [comment]
Thanks! Do you know when to check for updates for this? I was thinking of
contributing code myself.


On Wed, May 20, 2015 at 5:56 PM, Lunatixz <notifications@github.com> wrote:

> Closed #34 <https://github.com/Lunatixz/script.pseudotv.live/issues/34>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Lunatixz/script.pseudotv.live/issues/34#event-310075390>
> .
>



-- 
Thank you!

**Comment by Lunatixz** [comment]
https://twitter.com/PseudoTV_Live <-- for info, feel free to contribute.. Thanks
