### ISSUE TITLE
Autotune adding rules to all channels

### ISSUE THREAD

**Issue by usernamejusttogetonwith** [Lunatixz/script.pseudotv.live#38]
If I use auto-tune to set um my channels it adds a rule to "play in order" rule to every channel. I wish there was a way to remove all channel rules instead of going one channel at a time or just not have it add that rule on there. Over 60 channels takes a long time to mess with that. I starts playing the shows in order (not random) and seems to only play one show on the channel not the 3 or four that go on that channel.

**Comment by Lunatixz** [comment]
auto-tuning takes channel creation control away from the user. If you have preferences, then manually create the channel.
